### ISSUE TITLE
Feature: Setup a default limit for the maxHistory setting of tiller

### ISSUE THREAD

**Issue by tverhoeven** [gruntwork-io/terraform-kubernetes-helm#36]
Could this chart set a default, but configurable, value for the tiller maxHistory setting? This to prevent that the history created by helm/tiller release causes issues by having to many secrets stored. (Feature description: https://github.com/helm/helm/pull/2636)

The plan is that helm will set a default in v3: https://github.com/helm/helm/issues/5157

Then we do not manually need to cleanup the history.

**Comment by yorinasub17** [comment]
Hi @tverhoeven ,

If you are using the `k8s-tiller` submodule, you should be able to already configure the tiller max history using the input var `tiller_history_max`.

If you are instead using `kubergrunt helm deploy`, then indeed this feature is missing. Can you refile the issue in the `kubergrunt` repo so we can track it there?

**Comment by tverhoeven** [comment]
I'm actually using gke-cluster which then calls k8s-tiller. So I guess I need to log a ticket there that max history configuration is exposed.
