### ISSUE TITLE
Wrong output value for helm_client_tls_public_cert_pem

### ISSUE THREAD

**Issue by justinpa-asg** [gruntwork-io/terraform-kubernetes-helm#39]
Looking for public certificate but found private key. Copy/paste bug in outputs.tf?
```
output "helm_client_tls_public_cert_pem" {
  value       = module.helm_client_tls_certs.tls_certificate_key_pair_private_key_pem
```

**Comment by yorinasub17** [comment]
Yes indeed that is a copy paste bug. Thanks for reporting!

Opened PR https://github.com/gruntwork-io/terraform-kubernetes-helm/pull/40
