### ISSUE TITLE
Fails with error if create_resources set to false

### ISSUE THREAD

**Issue by stuart-c** [gruntwork-io/terraform-kubernetes-helm#42]
I'm getting the following error:

```
Error: Invalid index

  on .terraform/modules/k8s-namespace/main.tf line 52, in module "namespace_roles":
  52:   namespace   = kubernetes_namespace.namespace[0].id
    |----------------
    | kubernetes_namespace.namespace is empty tuple

The given key does not identify an element in this collection value.
```

The cause looks to be here:

https://github.com/gruntwork-io/terraform-kubernetes-helm/blob/master/modules/k8s-namespace/main.tf#L52

I think the fix would be to change that line to

`namespace = var.create_resources ? kubernetes_namespace.namespace[0].id : ""`

**Comment by yorinasub17** [comment]
Can you share which version of terraform you are using? I am not seeing this error on `0.12.9`, so it might be a behavior on older versions.

**Comment by yorinasub17** [comment]
For reference, here is the PR that adds a test to verify this behavior (https://github.com/gruntwork-io/terraform-kubernetes-helm/pull/43). Note that I didn't have to touch `k8s-namespace` to get the test passing.

**Comment by stuart-c** [comment]
This is with Terraform 0.12.11

**Comment by yorinasub17** [comment]
Got it. I just repro'd it.

**Comment by yorinasub17** [comment]
Just updated the PR with the fix. Can you try to see if it works with the branch `yori-address-create-resources`?

**Comment by efernandes-ANDigital** [comment]
Thanks for fixing this, I can confirm it all works fine. @yorinasub17  :)
